POST http://localhost:4001/api/users
Content-Type: application/json

{
  "email": "example@example.com",
  "username": "example",
  "password": "password123"
}

###################

GET http://localhost:4001/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NTUzY2M1MGE1OTkzZjg3YWM2OWQ2NyIsImVtYWlsIjoiZXhhbXBsZUBleGFtcGxlLmNvbSIsImlhdCI6MTY4MzMwNzcxN30.l6OAjO71pO2Qt51PYoKvFVSj_e0aNyvR1m8kkjzFzfM
