POST http://localhost:4001/api/users
Content-Type: application/json

{
  "email": "example@example.com",
  "username": "example",
  "password": "password123"
}

###################

GET http://localhost:4001/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NTUxMjgxNzk2OWU4ZDIxY2Q2MWE2YyIsImVtYWlsIjoiZXhhbXBsZUBleGFtcGxlLmNvbSIsImlhdCI6MTY4MzI5Njg5N30.5cfBfkXpEHfehy5rM7JfJSJKfBDOte1M4zAsIAMOYlA
